{% set name = "django-wildewidgets" %}
{% set version = "0.16.16" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/django-wildewidgets-{{ version }}.tar.gz
  sha256: 51451947d690c1fbf991a19fcbe55871f6de2d9605b7bd90ee96a9a0492b01b5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - django-crispy-forms
    - crispy-bootstrap5

test:
  imports:
    - wildewidgets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/caltechads/django-wildewidgets
  summary: django-wildewidgets is a Django design library providing several tools for building full-featured, widget-based web applications with a standard, consistent design, based on Bootstrap.
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - rxm7706
